# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **1 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).


## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.


In [1]:
# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')


Banco do Stark carregado!


## Execução guiada (base para a atividade)
Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**


In [2]:
# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')


=== CRIAR CONTAS ===
OK - Conta criada para: tony
OK - Conta criada para: pepper
OK - Conta criada para: banner

=== DEPÓSITOS ===
OK - Depósito realizado: 1000
OK - Depósito realizado: 500

=== SALDOS ===
SALDO tony = 1000.0
SALDO pepper = 500.0

=== SAQUE ===
OK - Saque realizado: 200
SALDO tony = 800.0

=== TRANSFERÊNCIA ===
OK - Transferência realizada: 100
SALDO tony = 700.0
SALDO pepper = 600.0

=== EXTRATO (tony) ===
EXTRATO: tony
 - ('deposito', 1000)
 - ('saque', 200)
 - ('transferencia_saida', 100)

TESTES NEGATIVOS (QA)

Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0

Teste N2 - Depósito negativo
OK - Depósito realizado: -100

Saldo após depósitos inválidos
SALDO tony = 600.0

Teste N3 - Saque acima do saldo
ERRO - Saldo insuficiente

Teste N4 - Transferência para conta inexistente
ERRO - Conta destino não encontrada

Teste N5 - Consulta de conta inexistente (saldo)
ERRO - Conta não encontrada: natasha

Teste N6 - Consulta de conta inexistente (extrato)
ERRO -

# PARTE 04 — Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente


## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:** Verificar que não é possível realizar um depósito com valor zero.
**Pré-condição:** A conta 'tony' existe e possui saldo de 700.0 (estado após o cenário inicial).
**Passos:**  
1.  Executar a operação `banco.depositar('tony', 0)`.
**Resultado esperado:** Uma mensagem de erro indicando que o valor do depósito deve ser maior que zero (ex: "ERRO - Valor do depósito deve ser > 0"). O saldo da conta 'tony' deve permanecer 700.0.
**Resultado obtido:** "OK - Depósito realizado: 0". O saldo da conta 'tony' foi atualizado para 700.0 + 0 = 700.0 (se apenas esta operação fosse realizada isoladamente, mas no fluxo total o saldo final foi 600.0 devido ao depósito negativo seguinte), e a operação foi considerada "OK".
**Status (Pass/Fail):** Fail  
**Evidência:**
```
Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0
```

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:** Verificar que não é possível realizar um depósito com valor negativo.
**Pré-condição:** A conta 'tony' existe e possui saldo de 700.0 (estado após o cenário inicial e possível depósito de 0).
**Passos:**  
1.  Executar a operação `banco.depositar('tony', -100)`.
**Resultado esperado:** Uma mensagem de erro indicando que o valor do depósito deve ser maior que zero (ex: "ERRO - Valor do depósito deve ser > 0"). O saldo da conta 'tony' deve permanecer 700.0 (ou o saldo anterior à operação).
**Resultado obtido:** "OK - Depósito realizado: -100". O saldo da conta 'tony' foi atualizado para 700.0 + (-100) = 600.0, e a operação foi considerada "OK".
**Status (Pass/Fail):** Fail  
**Evidência:**
```
Teste N2 - Depósito negativo
OK - Depósito realizado: -100
```

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:** Verificar que não é possível realizar um saque com valor superior ao saldo disponível.
**Pré-condição:** A conta 'tony' existe e possui saldo de 600.0 (estado após todos os depósitos e saques iniciais, incluindo os inválidos).
**Passos:**  
1.  Executar a operação `banco.sacar('tony', 100000)`.
**Resultado esperado:** Uma mensagem de erro indicando saldo insuficiente (ex: "ERRO - Saldo insuficiente"). O saldo da conta 'tony' deve permanecer 600.0.
**Resultado obtido:** "ERRO - Saldo insuficiente".
**Status (Pass/Fail):** Pass  
**Evidência:**
```
Teste N3 - Saque acima do saldo
ERRO - Saldo insuficiente
```

# PARTE 05 — Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo


## Template — Bug Report
**Título:** Sistema permite depósito com valor zero.
**Severidade (Baixa/Média/Alta):** Média
**Prioridade (Baixa/Média/Alta):** Média
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** O sistema `BancoDoStark` permite que um usuário realize um depósito com valor igual a zero, o que contradiz a regra de negócio que estabelece que o valor do depósito deve ser maior que zero. A operação é registrada como "OK".

**Passos para reproduzir:**  
1.  Inicializar o `BancoDoStark` e criar uma conta para 'tony' (ou usar uma conta existente).
2.  Realizar um depósito na conta 'tony' com valor 0: `banco.depositar('tony', 0)`.
3.  Verificar a saída da operação.

**Resultado esperado:** Uma mensagem de erro indicando que o valor do depósito deve ser maior que zero (ex: "ERRO - Valor do depósito deve ser > 0"). O saldo da conta não deve ser alterado e a operação não deve ser registrada como "OK".
**Resultado obtido:** "OK - Depósito realizado: 0". A operação é aceita.
**Evidência:**  
```
Teste N1 - Depósito com valor zero
OK - Depósito realizado: 0
```
**Impacto/Risco:** Permite que transações irrelevantes (depósitos de 0) sejam processadas e registradas, gerando ruído nos extratos e processamento desnecessário.

## Template — Bug Report
**Título:** Sistema permite depósito com valor negativo.
**Severidade (Baixa/Média/Alta):** Alta
**Prioridade (Baixa/Média/Alta):** Alta
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** O sistema `BancoDoStark` permite que um usuário realize um depósito com valor negativo, o que contradiz a regra de negócio que estabelece que o valor do depósito deve ser maior que zero. Esta operação resulta na redução do saldo da conta, comportando-se como um saque não validado, e é registrada como "OK".

**Passos para reproduzir:**  
1.  Inicializar o `BancoDoStark` e criar a conta 'tony'.
2.  Realizar um depósito inicial na conta 'tony' (ex: `banco.depositar('tony', 1000)`).
3.  Realizar um depósito na conta 'tony' com valor negativo: `banco.depositar('tony', -100)`.
4.  Verificar a saída da operação e o saldo atual da conta.

**Resultado esperado:** Uma mensagem de erro indicando que o valor do depósito deve ser maior que zero (ex: "ERRO - Valor do depósito deve ser > 0"). O saldo da conta não deve ser alterado e a operação não deve ser registrada como "OK".
**Resultado obtido:** "OK - Depósito realizado: -100". O saldo da conta 'tony' é reduzido pelo valor negativo.
**Evidência:**  
```
Teste N2 - Depósito negativo
OK - Depósito realizado: -100
Saldo após depósitos inválidos
SALDO tony = 600.0
```
**Impacto/Risco:** Violação crítica da integridade do saldo do usuário, permitindo saques não autorizados ou não validados sob o disfarce de um depósito.

## Template — Bug Report
**Título:** Sistema permite que usuário transfira fundos para a própria conta.
**Severidade (Baixa/Média/Alta):** Baixa
**Prioridade (Baixa/Média/Alta):** Média
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:** A regra de negócio especifica que um usuário não pode transferir fundos para si mesmo. No entanto, a implementação atual do método `transferir` na classe `BancoDoStark` não inclui uma validação para impedir que as contas de origem e destino sejam a mesma. Isso permite que um usuário realize uma transferência de sua própria conta para si mesmo, o que resulta em operações de débito e crédito redundantes no extrato.

**Passos para reproduzir:**  
1.  Inicializar o `BancoDoStark` e criar a conta 'tony'.
2.  Realizar um depósito inicial na conta 'tony' (ex: `banco.depositar('tony', 1000)`).
3.  Tentar transferir um valor da conta 'tony' para a própria conta 'tony': `banco.transferir('tony', 'tony', 50)`.
4.  Verificar a saída da operação e o extrato da conta 'tony'.

**Resultado esperado:** Uma mensagem de erro indicando que não é possível transferir para a própria conta (ex: "ERRO - Não é possível transferir para si mesmo"). O saldo da conta 'tony' não deve ser alterado e o extrato não deve registrar a transação.
**Resultado obtido:** A operação seria processada como "OK - Transferência realizada: 50", e o extrato de 'tony' registraria tanto uma saída quanto uma entrada do mesmo valor.
**Evidência:**  
```
# (Esta evidência é baseada na análise do código, já que o teste não foi executado no cenário providenciado.)
# Se a operação 'banco.transferir('tony', 'tony', 50)' fosse executada, a saída esperada seria:
OK - Transferência realizada: 50
# E no extrato de 'tony', apareceriam duas novas entradas:
#  - ('transferencia_saida', 50)
#  - ('transferencia_entrada', 50)
```
**Impacto/Risco:** Geração de entradas de extrato desnecessárias e confusão para o usuário, além de violação de uma regra de negócio explícita.

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.

In [3]:
# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

print('Pronto! Execute seus testes aqui.')


Pronto! Execute seus testes aqui.


## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.
